routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/







Route::get('/', 'ProductController@index');


Route::resource('products', 'ProductController');
Route::resource('categories', 'CategoryController');
Route::resource('manufacturers', 'ManufacturerController');
Route::resource('suppliers', 'SupplierController');


Auth::routes();

Route::get('/home', 'HomeController@index');

app/Manufacturer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Manufacturer extends Model
{
     public function products()
    {
        return $this->hasMany('App\Product');
    }
}

app/Http/Controllers/ManufacturerController.php
<?php

namespace App\Http\Controllers;

use App\Manufacturer;

use Illuminate\Http\Request;

class ManufacturerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $manufacturers = Manufacturer::all();

        return view ('manufacturer.index' , ['items' => $manufacturers]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        return view('manufacturer.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $manufacturer = new Manufacturer();
        $manufacturer->title = $request->title;
        $manufacturer->website_url = $request->website_url;
        $manufacturer->country = $request->country;
        

        $manufacturer->save();

        return redirect()->route('manufacturers.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Manufacturer  $manufacturer
     * @return \Illuminate\Http\Response
     */
    public function show(Manufacturer $manufacturer)
    {
        return view('manufacturer.show', ['manufacturer' => $manufacturer]); //////View nurodo folderi
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Manufacturer  $manufacturer
     * @return \Illuminate\Http\Response
     */
    public function edit(Manufacturer $manufacturer)
    {
        
        return view('manufacturer.form', [
            'manufacturer'=>$manufacturer,
            ]);
}
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Manufacturer  $manufacturer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Manufacturer $manufacturer)
    {
        
        $manufacturer->title = $request->title;
        $manufacturer->website_url = $request->website_url;
        $manufacturer->country = $request->country;
        

        $manufacturer->update();

        return redirect()->route('manufacturers.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Manufacturer  $manufacturer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Manufacturer $manufacturer)
    {
        $manufacturer->delete();
        return redirect()->route('manufacturers.index');
    }
}

resources/views/manufacturer/form.blade.php
@extends('layouts.app')


	@section('content')
		
		<h2>GAMINTOJU keitimas</h2>

		@if(isset($manufacturer))
			{!! Form::model($manufacturer, [
			'route' => ['manufacturers.update', $manufacturer->id],
			'method' => 'put'
			]) !!}
			@else
				{!! Form::open(['route' => 'manufacturers.store', 'method' => 'post']) !!}
			@endif
						

			<div class="from-group">    
			{!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Title'])!!}
			</div>
			<div class="from-group">    
			{!! Form::text('website_url', null, ['class' => 'form-control', 'placeholder' => 'Title'])!!}
			</div>
			<div class="from-group">    
			{!! Form::text('country', null, ['class' => 'form-control', 'placeholder' => 'Title'])!!}
			</div>
			
			

			{!! Form::submit('Save' ,['class' => 'btn-primary']) !!}
			

		{!! Form::close() !!}



		@if(isset($manufacturer))
			{!! Form::open([
			'route' => ['manufacturers.destroy', $manufacturer->id],
			'method' => 'delete' 
			])
			 !!}
				{!! Form::submit('Delete' , ['class' => 'btn btn-danger'])!!}
			 
			{!! Form::close() !!}
		@endif

@endsection

resources/views/manufacturer/index.blade.php
@extends('layouts.app')

	@section('content')
	
	<div class="container">
		<div class="row">
		<h2>GAMINTOJU SARASAS</h2>
			<div class="col-md-6 col-md-offset-3">
				<a class="btn btn-success" href="{{ route('manufacturers.create') }}">SUKURTI NAUJA GAMINTOJA</a>
				<hr>
					<ul>
    	   			 @foreach ($items as $manufacturer) 
		    		    <li>
					    	<a href="{{route('manufacturers.show',['id'=>$manufacturer->id])}}">{{ $manufacturer->title }}</a>
					    </li>
					    <li>
					    	<a class="btn btn-primary marginB2" href="{{ route('manufacturers.edit', $manufacturer->id) }}">koreguoti</a>
					    </li>
					    <hr>
		    		@endforeach
					</ul>
			</div>
		</div>
	</div>
		
		
	@endsection

resources/views/manufacturer/show.blade.php
@extends('layouts.app')

	@section('content')

	<a href="#" class="list-group-item active"><h1>Galimi gamintojai:</h1>
    
  </a>
	<div class="list-group">

  <a href="#" class="list-group-item">{{ $manufacturer->title }}</a>
	
 		 
 		 @foreach ($manufacturer->products as $product) 
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				<img src="{{ $product->image_url}} ">
					<div class="caption">
						
						<p> 
							
							@if ($product->manufacturer)
							<strong> GAMINTOJAS: {{ $product->manufacturer->title}} </strong>
							@endif 
						 </p>
						 <p>
						 	<a href="{{route('manufacturers.edit', $manufacturer->id) }}" class="btn btn-default" role="button" class="btn btn-primary" role="button">PERZIURETI</a> <a href="">Button</a>
						 </p>
					</div>			
			</div>
		</div>
		 @endforeach	

	</div>

@endsection