routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/







Route::get('/', 'ProductController@index');


Route::resource('products', 'ProductController');
Route::resource('categories', 'CategoryController');
Route::resource('manufacturers', 'ManufacturerController');
Route::resource('suppliers', 'SupplierController');


Auth::routes();

Route::get('/home', 'HomeController@index');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function products()
    {
        return $this->hasMany('App\Product');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;

use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();

        return view ('category.index' , ['items' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category = new Category();
        $category->title = $request->title;
                

        $category->save();

        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view ('category.show', ['category' => $category]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        
        return view('category.form', [
            'category'=>$category            
            ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        
        $category->title = $request->title;
                

        $category->update();

        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->route('categories.index');
    }
}

resources/views/category/form.blade.php
@extends('layouts.app')


	@section('content')
		
		<h2>KATEGORIJOS keitimas</h2>

		@if(isset($category))
			{!! Form::model($category, [
			'route' => ['categories.update', $category->id],
			'method' => 'put'
			]) !!}
			@else
				{!! Form::open(['route' => 'categories.store', 'method' => 'post']) !!}
			@endif
						

			<div class="from-group">    
			{!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Title'])!!}
			</div>
			
			

			{!! Form::submit('Save' ,['class' => 'btn-primary']) !!}
			

		{!! Form::close() !!}



		@if(isset($category))
			{!! Form::open([
			'route' => ['categories.destroy', $category->id],
			'method' => 'delete' 
			])
			 !!}
				{!! Form::submit('Delete' , ['class' => 'btn btn-danger'])!!}
			 
			{!! Form::close() !!}
		@endif

@endsection

resources/views/category/index.blade.php
	@extends('layouts.app')

	@section('content')
	
	<div class="container">
		<div class="row">
		<h2>KATEGORIJU SARASAS</h2>
			<div class="col-md-6 col-md-offset-3">
				<a class="btn btn-success" href="{{ route('categories.create') }}">SUKURTI NAUJA KATEGORIJA</a>
				<hr>
					<ul>
    	   			 @foreach ($items as $category) 
		    		    <li>
					    	<a href="{{route('categories.show',['id'=>$category->id])}}">{{ $category->title }}</a>
					    </li>
					    <li>
					    	<a class="btn btn-primary marginB2" href="{{ route('categories.edit', $category->id) }}">koreguoti</a>
					    </li>
					    <hr>
		    		@endforeach
					</ul>
			</div>
		</div>
	</div>
		
		
	@endsection

resources/views/category/show.blade.php
@extends('layouts.app')

	@section('content')

	<a href="#" class="list-group-item active"><h1>Galimos kategorijos:</h1>
    
  </a>
	<div class="list-group">

  <a href="#" class="list-group-item">{{ $category->title }}</a>
	
 		 
 		 @foreach ($category->products as $product) 
		<div class="col-sm-6 col-md-4">
			<div class="thumbnail">
				<img src="{{ $product->image_url}} ">
					<div class="caption">
						
						<p> 
							@if ($product->category)
							<strong> KATEGORIJA: {{ $product->category->title}} </strong>
							@endif
							
						 </p>
						 
						 	 <p>
						 	<a href="{{route('categories.edit', $category->id) }}" class="btn btn-primary">EDIT</a>
						 </p>
						 	
					</div>			
			</div>
		</div>
		 @endforeach	

	</div>

@endsection