routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/







Route::get('/', 'ProductController@index');


Route::resource('products', 'ProductController');
Route::resource('categories', 'CategoryController');
Route::resource('manufacturers', 'ManufacturerController');
Route::resource('suppliers', 'SupplierController');


Auth::routes();

Route::get('/home', 'HomeController@index');

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    public function products()
    {
    	return $this->hasMany('App\Product');
    }
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use App\Supplier;
use Illuminate\Http\Request;

class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $suppliers = Supplier::all();
        return view ('supplier.index' , ['items' => $suppliers]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('supplier.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $supplier = new Supplier();
        $supplier->title = $request->title;

        $supplier->save();
        return redirect()->route('suppliers.index');
    }

                


    /**
     * Display the specified resource.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function show(Supplier $supplier)
    {
        return view ('supplier.show', ['supplier' => $supplier]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function edit(Supplier $supplier)
    {
        return view ('supplier.form', [
            'supplier' =>$supplier,
            ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Supplier $supplier)
    {
       $supplier->title = $request->title;

       $supplier->update();
        return redirect()->route('suppliers.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Supplier  $supplier
     * @return \Illuminate\Http\Response
     */
    public function destroy(Supplier $supplier)
    {
        $supplier->delete();
        return redirect()->route('suppliers.index');
    }
}

resources/views/supplier/form.blade.php
@extends('layouts.app')
@section('content')
@if(isset($supplier))
<h2>Supplier redagavimas:</h2>
{{-- editinimo forma --}}
{!! Form::model($supplier,['route' => ['suppliers.update',$supplier->id], 'method' => 'put']) !!}
@else
<h2>Supplier sukūrimas:</h2>
{{-- creat forma --}}
{!! Form::open(['route' => 'suppliers.store', 'method' => 'post']) !!}
@endif
<div class="form-group">
    {!!Form::label('title', 'Title')!!}
    {!!Form::text('title', null, ['class' => 'form-control','placeholder'=>'Title']) !!}
</div>
{!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
{!! Form::close() !!}
{{-- delete forma --}}
@if(isset($supplier))
{!! Form::open(['route' => ['suppliers.destroy', $supplier->id], 'method' => 'delete']) !!}
{!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
{!! Form::close() !!}
@endif
@endsection

resources/views/supplier/index.blade.php
@extends('layouts.app')

	@section('content')
	
	<div class="container">
		<div class="row">
		<h2>TIEKEJU SARASAS</h2>
			<div class="col-md-6 col-md-offset-3">
				<a class="btn btn-success" href="{{ route('suppliers.create') }}">SUKURTI NAUJA TIEKEJA</a>
				<hr>
					<ul>
    	   			 @foreach ($items as $supplier) 
		    		    <li>
					    	<a href="{{route('suppliers.show',['id'=>$supplier->id])}}">{{ $supplier->title }}</a>
					    </li>
					    <li>
					    	<a class="btn btn-primary marginB2" href="{{ route('suppliers.edit', $supplier->id) }}">koreguoti</a>
					    </li>
					    <hr>
		    		@endforeach
					</ul>
			</div>
		</div>
	</div>
		
		
	@endsection

resources/views/supplier/show.blade.php
@extends('layouts.app')
@section('content')
<h2>Supplier: {{ $supplier->title }}</h2>
<a href="{{route('suppliers.edit', $supplier->id) }}" class="btn btn-warning marginB">Edit supplier</a>
<div class="row">
    @foreach ($supplier->products as $product) 
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img src="{{$product->image_url}}" alt="{{ $product->title }}">
            <div class="caption">
                <h3>{{ $product->title }}</h3>
                <p>{{ $product->description }}</p>
                <p>
                    Kaina: {{ $product->price }}. 
                    Kiekis: {{ $product->quantity }}.
                </p>
                <p>
                    @if ($product->category)
                    <strong>Kategorija: </strong>{{ $product->category->title }}
                    @endif
                    
                    @if ($product->manufacturer)
                    <br>
                    <strong>Gamintojas: </strong>{{ $product->manufacturer->title }}
                    @endif
                    @if ($product->supplier)
                    <br>
                    <strong>Supplier: </strong>{{ $product->supplier->title }}
                    @endif
                </p>
                <a class="btn btn-primary" href="{{ route('products.show', ['id' => $product->id]) }}">Peržiūrėti</a>
            </div>
        </div>
    </div>
    @endforeach
</div>
@endsection